package PAYTMPE_POR;

import org.openqa.selenium.WebDriver;

public class PAYTMPE_UTILS {

	
	public static WebDriver driver;
    APPLY_NEW_FRD_PAGE UFD=new APPLY_NEW_FRD_PAGE(driver);
	CHANGE_PASSWORD_PAGE UCPP=new CHANGE_PASSWORD_PAGE(driver);
	CREATE_NEW_TICKET_PAGE UCNU=new CREATE_NEW_TICKET_PAGE(driver);
	DASHBOARDPAGE UDP=new DASHBOARDPAGE(driver);
	EXCHANGE_MONEY_PAGE UEM=new EXCHANGE_MONEY_PAGE(driver);
	FORGETPASSWORD   UFP=new FORGETPASSWORD(driver);
	public static HOMEPAGE UHP=new HOMEPAGE(driver);
	LOANS_NEW_LOAN_PAGE01 UNLA=new   LOANS_NEW_LOAN_PAGE01(driver);
	public static LOGINPAGE ULP=new  LOGINPAGE(driver);
	NEW_PAYMENT_REQPAGE UNPRP=new NEW_PAYMENT_REQPAGE(driver);
	REDEEM_GIFT_VOCHER_PAGE URGVP=new  REDEEM_GIFT_VOCHER_PAGE(driver);
	SEND_MONEY_PAGE   USMP=new   SEND_MONEY_PAGE(driver);
	WIRE_TRASFER_PAGE  UWTP=new   WIRE_TRASFER_PAGE(driver);
	 REGISTERPAGE  URP=new  REGISTERPAGE (driver);
}
